# -*- coding: utf-8 -*-
"""Parking_segment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oDTA9vTFbnF0UDhrJrs40cq2iLrmQBH
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

img_path = '/content/Capture.JPG'

img = cv2.imread(img_path)
plt.imshow(img[...,::-1])

# print(lines)

def draw_lines(img_path):
    img = cv2.imread(img_path)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    for aperturesize in [5,7]:
        edges = cv2.Canny(gray,100,250,apertureSize = aperturesize)
        lines = cv2.HoughLines(edges,1,np.pi/180,30)
        for rho,theta in lines[0]:
            a = np.cos(theta)
            b = np.sin(theta)
            x0 = a*rho
            y0 = b*rho
            x1 = int(x0 + 1000*(-b))
            y1 = int(y0 + 1000*(a))
            x2 = int(x0 - 1000*(-b))
            y2 = int(y0 - 1000*(a))
            cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)
    return(img)

img = draw_lines('/content/Capture.JPG')

plt.imshow(img)
plt.show()

cv2.imwrite('line_drawn_image.jpg',img)

