# Generated by Django 2.2.5 on 2019-09-19 07:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=1000)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Notification',
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DISABLED', 'DISABLED'), ('SENIOR', 'SENIOR')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserNotification')),
            ],
            options={
                'verbose_name': 'User Category',
                'verbose_name_plural': 'User Categories',
            },
        ),
        migrations.CreateModel(
            name='TokenIssuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1000)),
                ('active_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserNotification')),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserNotification')),
            ],
        ),
        migrations.CreateModel(
            name='BulkMessageIssuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('DISABLED', 'DISABLED'), ('SENIOR', 'SENIOR')], max_length=15)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserNotification')),
            ],
        ),
    ]
